### ISSUE TITLE
关于公式(5)的疑惑

### ISSUE THREAD

**Issue by linklist2** [MingSun-Tse/Regularization-Pruning#3]
您好作者，首先感谢您的工作。但是请原谅我的愚钝，虽然公式（5）给了附录证明，但是我仍旧想请教一下附录里的公式该如何理解。。。
![image](https://user-images.githubusercontent.com/46252413/151106324-dea4d322-ba6c-43e8-a80b-90db12650e00.png)
第一个公式就懵住了，我目前的关于泰勒展开的知识只有这个：
![image](https://user-images.githubusercontent.com/46252413/151107473-0fd0a809-4348-49e6-9396-dadba01b4bcb.png)
但是似乎和附录的公式又差了个1/2.

**Comment by MingSun-Tse** [comment]
Hi @linklist2 , Thanks for your interest in our work! Your understanding is _correct_, We actually drop all the 1/2 factors (e.g., in (11), there should also be a 1/2 before the L2 penalty term) for cleaner notation. The original version should be: adding 1/2 at 
- RHS of (10) before the 1st term
- RHS of (11) before the 2nd term
- RHS of (12) before the 1st term
- RHS of (13) before the 1st and 2nd terms

Then you'll find (14) still holds when you compare (12) to (13). _It is simply like adding 1/2 at both sides of an equation_.

As for other terms in the Taylor expansion pic you posted, f(X*) is a constant which is accounted for by the constant C in our formula; the 1st-order derivatives are (assumed to be) zero, given the network is a converged one (this only _roughly_ holds in practice as we mention in the paper, following previous works like OBD); the o(*) term is also dropped because we adopt the "local quadratic approximation" actually also following previous works like OBD. 

Hope this can help clear your confusion! Let me know if you have more.

**Comment by linklist2** [comment]
@MingSun-Tse 谢谢，我推理了一下确实不影响结论的成立。
